### ISSUE TITLE
Add pt_BR FAQ

### ISSUE THREAD

**Issue by rodolfobandeira** [OpenBSD-BR/openbsd-br.org#3]
Add pt_BR FAQ

**Comment by egypcio** [comment]
- [ ] Restore CVS steelix's (bsdfrog.org) repository backup
- [ ] Organize OpenBSD's, and its related projects, translated contents (pt_BR only)
- [ ] Add existing pf User's Guide in pt_BR to the website
- [ ] Update (translate) the existing "guide" to its current version
- [ ] Get feedback, and work with current OpenBSD's FAQ

**Comment by ggrigon** [comment]
@egypcio conseguiu os arquivos ai?!

**Comment by egypcio** [comment]
https://github.com/OpenBSD-BR/openbsd-faq-br

**Comment by ggrigon** [comment]
closing it, since we have a dedicated repo for the faq
